### ISSUE TITLE
Improving before publishing as library

### ISSUE THREAD

**Issue by enormandeau** [enormandeau/rust_seq#1]
Hi @natir

Thanks for the help with the `fasta_reader` return type.

I'd like to release rust_seq, maybe under another name, as a library. I would like to use this functionality at least for myself instead of copy-pasting these helper functions in my sequence projects.

What do you think should be done before I can release this code?

**Comment by enormandeau** [comment]
As you can see, I'm fairly new to Rust but I want to use 2020 to become good at it and start doing real projects with it, especially porting Python code (or prototypes) that are too slow.

**Comment by natir** [comment]
Hi @enormandeau,

First what is your objectif: learn rust or build a library to easily reads and write fasta compresse or not ?

If your main objectif is learning rust you can continue to write this code and use it in your personal project you didn't need to release it in crates.io to use it in other project. You can define a repository as dependency as Cargo.toml.

```
rust_seq =  { git = "https://github.com/enormandeau/rust_seq" }
```


If you what build a library usable by other people, you need to move all `main.rs` in `lib.rs`. And before publish you crate on crates.io I think you need:
- write test in the [classic rust way](https://doc.rust-lang.org/book/ch11-01-writing-tests.html)
- replace your own compression detection by niffler when new api was release
- replace fast{a|q}_{writer|reader} by fastx_{writer|reader} when the issue rust-bio/rust-bio/pull/222 was merge and release
- setup CI thing to be sure your test passed at each commit

All this stuff is my opinion of a very unexperienced rust writer bioinformaticien. I'm probably wrong, don't blindly follow my advice.

**Comment by enormandeau** [comment]
Thanks. I will probably move all the code to `lib.rs` and keep this as a repository. I forgot about using a repository directly in Cargo.toml. I'll try this before I decide to publish a crate.

What would be the main advantages of using niffler? If I see the following, what am I potentially missing?
- Don't rely on the extension to guess the file type
- More compression types recognized

I'm planning to use fasta/fasta.gz and fastq/fastq.gz. I've been using the extension for years in my Python scripts without any problem, but I can see niffler is probably better!

**Comment by natir** [comment]
> What would be the main advantages of using niffler?
You miss the main advantage for me, it's not your code so it's not your bug.

I prefer never trust the user, the user makes errors or weired thing every time. But I'm maybe to strict.
