### ISSUE TITLE
Poor speed gain over Python

### ISSUE THREAD

**Issue by enormandeau** [enormandeau/rust_seq#3]
@natir

I'm trying `rust_seq` and comparing it against similar code in Python and the Rust code, which only iterates over sequences and writes them in another file, is only 5.8 times faster than the Python code, and the Python code actually does something more than just reading and writing the files.

Would you have an idea what makes it so slow? In Python, I use my own Fastq class and sequence iterator rather than the biopython one, since I found that biopython was much slower.

Could Rust-Bio be much slower? Is flate2 slow?

Here is the code:

```Rust
use std::env;
//use std::str;

extern crate rust_seq;
use rust_seq::*;

// Quality recoding

fn main() {
    let args: Vec<String> = env::args().collect();
    println!("{:?}", args);

    // Parse user input
    let input_filename = &args[1];
    let output_filename = &args[2];

    // Open reader an writer
    let sequences = fastq_reader(&input_filename);
    let mut outwriter = fastq_writer(&output_filename);

    // Iterate over sequences
    for seq in sequences.records() {
        let s = seq.unwrap().clone();
        outwriter.write_record(&s).unwrap();
    }
}
```

**Comment by enormandeau** [comment]
Ah, maybe the clone?

**Comment by enormandeau** [comment]
The other suspect is the `BufReader`  and `BufWriter` have declared sizes. See `with_capacity` below:

```Rust
pub fn reader(filename: &str) -> Box<dyn BufRead> {
    let path = Path::new(filename);
    let file = match File::open(&path) {
        Err(why) => panic!("couldn't open {}: {}", path.display(), why.description()),
        Ok(file) => file,
    };

    if path.extension() == Some(OsStr::new("gz")) {
        Box::new(BufReader::with_capacity(
            128 * 1024,
            read::GzDecoder::new(file),
        ))
    } else {
        Box::new(BufReader::with_capacity(128 * 1024, file))
    }
}

/// Write normal or compressed files seamlessly
/// Uses the presence of a `.gz` extension to decide
// Attempting to have a file writer too
pub fn writer(filename: &str) -> Box<dyn Write> {
    let path = Path::new(filename);
    let file = match File::create(&path) {
        Err(why) => panic!("couldn't open {}: {}", path.display(), why.description()),
        Ok(file) => file,
    };

    if path.extension() == Some(OsStr::new("gz")) {
        Box::new(BufWriter::with_capacity(
            128 * 1024,
            write::GzEncoder::new(file, Compression::default()),
        ))
    } else {
        Box::new(BufWriter::with_capacity(128 * 1024, file))
    }
}
```

**Comment by enormandeau** [comment]
I saw that in niffler you didn't use buffer sizes like this. Would it be faster without the sizes?

**Comment by enormandeau** [comment]
I'm guessing Rust-Bio does at least three things:
- Have solid/heavy parsers
- Perform some checks on the ids, desc, seq, qual...
- Convert seq and qual to [u8] internally when reading
- Reconvert seq and qual to utf8 when writing

What I do in Python:
- Have lightweight parser
- Perform no checks whatsoever
- Keep sequence and quality as strings

Since I use these reader/writer functions to read one sequence at a time and perform actions, there is no need to re-encode the sequence and quality to save memory.

**Comment by natir** [comment]
First thing rust-bio wrappe is input in buffer so you didn't need to add buffer. I need to create a pull request to allow user to choose the buffer size. I think `flate2` have a buffer too. So if you realy want have control on buffer size work on uncompress file and use [my version of rust-bio](https://github.com/natir/rust-bio) before I create my pull request.

I actually work on benchmark on uncompressed fasta parsing you can found code her https://github.com/natir/fast_bench/. I include some C, C++ and Rust code. I see after 8M the buffer size hasn't a huge impact on computation time, 8M is the default size of Rust buffer.

And in fact file parsing as impact by I/O bound not by code speed, so didn't expect a huge improvement on only file reading.

About the effect of check on parsing time, for my benchmark I create a parser without any check (`buf_read_map`) and I just divide computation time by two (on SSD). Moreover this parser use memory mapping to read file.

You can also replace rust-bio by [needletail](https://github.com/onecodex/needletail) (less check was performed) but I didn't see a huge improvement in my benchmark.
